//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioDocumentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DeptoCode { get; set; }
        public string DeptoName { get; set; }
        public int DeptoOwner { get; set; }
        public string UserRole { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
