//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioDocumentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string PermissionType { get; set; }
        public Nullable<short> DirectorateId { get; set; }
        public Nullable<int> DeptoCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Directorate Directorate { get; set; }
        public virtual User User { get; set; }
    }
}
